title: OBJECT ORIENTED PROGRAMMING PORFOLIO
description: by Noel Justine Diaz
show_downloads: false

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css/custom.css

baseurl: "/7OOP-PORTFOLIO"

